---
services:
  jenkins:
    container_name: jenkins-whanos
    build: jenkins/
    image: jenkins:lts-jdk17
    ports:
      - "8080:8080"
    restart: unless-stopped
    volumes:
      - jenkins-whanos-data:/var/jenkins_home
      - ./jenkins/casc.yml:/var/jenkins_home/casc_configs/casc.yaml:ro
      - ./jenkins/job_dsl.groovy:/opt/jenkins/job_dsl.groovy:ro
      - ./jenkins/scripts/deploy.sh:/opt/jenkins/deploy.sh:ro
      - ./images:/opt/jenkins/images:ro
      - ./jenkins/helm:/opt/jenkins/helm:ro
      - /var/run/docker.sock:/var/run/docker.sock
      - ${HOME}/.kube:/var/jenkins_home/.kube:ro
    environment:
      CASC_JENKINS_CONFIG: "/var/jenkins_home/casc_configs"
      ADMIN_PASSWORD: "admin"
      IMAGE: "/opt/jenkins/image"
    entrypoint:
      - "/usr/bin/tini"
      - "--"
      - "/usr/local/bin/jenkins.sh"

  registry:
    image: registry:2
    container_name: whanos-registry
    ports:
      - "5000:5000"
    restart: unless-stopped
    volumes:
      - registry-data:/var/lib/registry
      - ./registry/config.yml:/etc/docker/registry/config.yml:ro

  registry-ui:
    image: joxit/docker-registry-ui:latest
    container_name: whanos-registry-ui
    restart: unless-stopped
    ports:
      - "8081:80"
    environment:
      - REGISTRY_TITLE=Whanos Registry
      - REGISTRY_URL=http://localhost:5000
      - DELETE_IMAGES=true
    depends_on:
      - registry

volumes:
  jenkins-whanos-data: {}
  registry-data: {}
