---
services:
  jenkins:
    container_name: jenkins-whanos
    build: jenkins/
    image: jenkins:lts-jdk17
    ports:
      - "8080:8080"
    restart: unless-stopped
    volumes:
      - jenkins-whanos-data:/var/jenkins_home
      - ./jenkins/casc.yml:/var/jenkins_home/casc_configs/casc.yaml:ro
      - ./jenkins/job_dsl.groovy:/opt/jenkins/job_dsl.groovy:ro
      - ./image:/opt/jenkins/image:ro
    environment:
      CASC_JENKINS_CONFIG: "/var/jenkins_home/casc_configs"
      ADMIN_PASSWORD: "admin"
      IMAGE: "/opt/jenkins/image"
    entrypoint:
      - "/usr/bin/tini"
      - "--"
      - "/usr/local/bin/jenkins.sh"

volumes:
  jenkins-whanos-data: {}
