---
{{- $release := .Release.Name -}}
{{- $vals := .Values -}}
{{- $resources := $vals.deployment.resources -}}
{{- $ports := $vals.deployment.ports -}}
{{- $replicas := default 1 $vals.deployment.replicas -}}
{{- $img := $vals.image -}}
{{- $imageName := $img.name -}}
{{- $imageRepo := $img.repository -}}
{{- $imageTag := default "latest" $img.tag -}}
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $release }}-deploy
  annotations:
    rollme: {{ randAlphaNum 5 | quote }}
spec:
  replicas: {{ $replicas }}
  selector:
    matchLabels:
      app: {{ $release }}
  template:
    metadata:
      labels:
        app: {{ $release }}
      annotations:
        rollme: {{ randAlphaNum 5 | quote }}
    spec:
      containers:
      - name: {{ $imageName }}
        image: {{ $imageRepo }}:{{ $imageTag }}
        {{- if $resources }}
        resources: {{ $resources | toJson }}
        {{- end }}
        {{- if $ports }}
        ports:
          {{- range $ports }}
          - containerPort: {{ . }}
          {{- end }}
        {{- end }}

{{- if $ports }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ $release }}-loadbalance
spec:
  type: LoadBalancer
  ports:
    {{- range $ports }}
    - targetPort: {{ . }}
      protocol: TCP
      port: {{ . }}
      name: {{ . | quote }}
    {{- end }}
  selector:
    app: {{ $release }}
{{- end }}
