name: Update Mirror

on:
  push:
    branches:
      - main

jobs:
  Push:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v1
        with:
          submodules: true
          ref: main
      - name: Push to private repository
        uses: pixta-dev/repository-mirroring-action@v1
        with:
          target_repo_url:
            git@github.com:skignes/whanos.git
          ssh_private_key:
            ${{ secrets.SSH_KEY }}
